# Kegs
tap "nikitabobko/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

# CLI Tools
brew "certbot"
brew "cmake"
brew "dive"
brew "docker"
brew "docker-compose"
brew "eza"
brew "fzf"
brew "ghq"
brew "git"
brew "go"
brew "golangci-lint"
brew "gzip"
brew "helm"
brew "hyperkit"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "lazygit"
brew "maven"
brew "minikube"
brew "neovim"
brew "openshift-cli"
brew "pnpm"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "tree"
brew "uv"
brew "vim"
brew "wget"
brew "yadm"
brew "z"

# Apps
cask "aerospace" # Tiling window manager
cask "kap"
cask "obsidian"
cask "itsycal"
cask "spotify" # Must have
cask "tableplus"
