import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux", "new-session", "-A", "-D", "-s", "main"]

[window]
padding = { x = 10, y = 10 }
opacity = 0.8
blur = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "BitstromWera Nerd Font Propo", style = "Regular" }
size = 16

[env]
TERM = "alacritty"
